### PR TITLE
fixes url control + rtp info

### PR DESCRIPTION
**Pull request by lucaszanella**
fixes the problem of some cameras providing no control url and also when some cameras do not provide the rtp-info header

### CODE REVIEW

**Comment by scottlamb** [comment]
Could you add a test to `parse.rs` with the data from this camera, similar to the others?

`base_url` is no longer used. I'd just keep around the slash form as `base_url` (the `alt_` prefix doesn't make sense if it's not an alternative to anything).

And please fix the CI failures.

**Comment by lucaszanella** [comment]
Almost everything fixed.

Please look at the remaining failures.

gw camera is failing because of our new approach with the `/` thing:

```
thread 'client::parse::tests::dahua_h264_aac_onvif' panicked at 'assertion failed: `(left == right)`
  left: `"rtsp://192.168.5.111:554/cam/realmonitor/trackID=0"`,
 right: `"rtsp://192.168.5.111:554/cam/trackID=0"`', src/client/parse.rs:624:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

could you test if the camera accepts `rtsp://192.168.5.111:554/cam/realmonitor/trackID=0`? Maybe it accepts both, since this fix is so common even live555 uses it?

**Comment by scottlamb** [comment]
That's the Dahua one. I just checked: yes, it accepts that URL.

```
SETUP rtsp://192.168.5.112/cam/realmonitor/trackID=0 RTSP/1.0
Authorization: Digest username="admin", realm="Login to a6915d5e7554b990e68381626d6c179e", nonce="567825442ff73b01cf6d932ce11b90a7", uri="rtsp://192.168.5.112/cam/realmonitor/trackID=0", response="ca249335d1ea2b5058cba507f0d14f28"
CSeq: 3
Transport: RTP/AVP/TCP;unicast;interleaved=0-1
User-Agent: moonfire-rtsp test
x-Dynamic-Rate: 1

RTSP/1.0 200 OK
CSeq: 3
Session: 889255551916;timeout=60
Transport: RTP/AVP/TCP;unicast;interleaved=0-1;ssrc=300E64B0
x-Dynamic-Rate: 1
```

**Comment by lucaszanella** [comment]
Can you provide me with a describe for it then so I can update the test?

**Comment by scottlamb** [comment]
describe response from the same session:

```
RTSP/1.0 200 OK
CSeq: 2
x-Accept-Dynamic-Rate: 1
Content-Base: rtsp://192.168.5.112/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif/
Cache-Control: must-revalidate
Content-Length: 705
Content-Type: application/sdp

v=0
o=- 2252201715 2252201715 IN IP4 0.0.0.0
s=Media Server
c=IN IP4 0.0.0.0
t=0 0
a=control:*
a=packetization-supported:DH
a=rtppayload-supported:DH
a=range:npt=now-
m=video 0 RTP/AVP 96
a=control:trackID=0
a=framerate:30.000000
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=640032;sprop-parameter-sets=Z2QAMqw8a4F8BUabgoCCoAAAAwAgAAAHkIAA,aO4xshsA
a=recvonly
m=audio 0 RTP/AVP 97
a=control:trackID=1
a=rtpmap:97 MPEG4-GENERIC/48000
a=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1188
a=recvonly
m=application 0 RTP/AVP 107
a=control:trackID=4
a=rtpmap:107 vnd.onvif.metadata/90000
a=recvonly
```

**Comment by lucaszanella** [comment]
I'd need the PLAY response too, as this is a different camera so I'm getting

```
running 1 test
thread 'client::parse::tests::gw_sub' panicked at 'called `Result::unwrap()` on an `Err` value: "RTP-Info contains unknown stream rtsp://192.168.1.110:5049/H264/video"', src/client/parse.rs:1171:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test client::parse::tests::gw_sub ... FAILED

```

on the gw_sub test. Should I do something different for `gw_main`? Also I think I need dahua too for `dahua_h264_aac_onvif`. There are the 3 failing tests. `gw_sub` is almost working except for play, and I don't know what to do in `gw_main`, is it a different camera?

**Comment by lucaszanella** [comment]
Take a look at the modifications: https://github.com/scottlamb/retina/pull/12/commits/637eba7334c2befe166a83a5b0cd8cd80b44356d

it's a different camera so I changed some of the aspects

**Comment by lucaszanella** [comment]
If you prefer, I can edit the dahua and gw setup/play messages manually, but this would not be good. It'd be nice to have the files so I can send the PR and then focus on the other parts. When you have a little time, please let me know what to do.

**Comment by scottlamb** [comment]
Okay, thanks for your patience as I read through this confused jumble of interop behavior as mentioned in my last comment on #9.

Anyway, I confused things by giving you output from a different camera than I'd checked in, but actually: neither of those cameras' test data files change at all. The test data files are just the camera's responses, and both cameras seem to respond in the same way no matter which of those two `SETUP` URLs we send.

**Comment by lucaszanella** [comment]
Now I'm more confused, I don't know what to do. The outputs should have changed. Did you forget and test with your branch instead of mine? Because mine has the new URLs to try.

**Comment by scottlamb** [comment]
The URLs we send change, and so the test asserts relating to that in `parse.rs` itself need to change to match. But the actual responses from the cameras in testdata don't seem any different in my tests (and in hindsight, I think that makes sense, they don't just repeat back the URLs we sent).

**Comment by lucaszanella** [comment]
ok everything works except for `dahua_h264_aac_onvif` which fails at https://github.com/lucaszanella/retina/blob/529203dea9ce6cde2ce0d0ebe88cdcf7e75ed114/src/client/parse.rs#L677 with

`"RTP-Info contains unknown stream rtsp://192.168.5.111:554/cam/trackID=0"`

which comes from https://github.com/lucaszanella/retina/blob/529203dea9ce6cde2ce0d0ebe88cdcf7e75ed114/src/client/parse.rs#L533

I don't knwo what to do about it but when fixed then do you think it's possible to merge?

**Comment by scottlamb** [comment]
> "RTP-Info contains unknown stream rtsp://192.168.5.111:554/cam/trackID=0"

Yeah, that's what I was referring to with the GW Security camera's RTP-Info url not matching the live555 way of joining. I think where this is returning an error, we should change it to log a warning and skip to the next iteration of the `for s in rtp_info.as_str().split(',') {` loop.

Then yes, we can merge!

**Comment by lucaszanella** [comment]
Ok I did this:

https://github.com/lucaszanella/retina/commit/299c8348a4ff9f3c9ba532afd04662e32cbafb09

but then I get

```
super::parse_play(&response(include_bytes!("testdata/dahua_play.txt")), &mut p).unwrap();
        match &p.streams[0].state {
            StreamState::Init(s) => {
                assert_eq!(s.initial_seq, Some(47121));  //// <---------------------- assert error
                assert_eq!(s.initial_rtptime, Some(3475222385));
            }
            _ => panic!(),
        };
```

I guess no track is being selected

**Comment by scottlamb** [comment]
Oh, you're still using the GW-like joining, not the live555-like joining. The Dahua `RTP-Info` should parse with the latter.

(I'm assuming you want to fix this yourself, but let me know if you prefer I do it. I have this all fresh in my mind after looking at it yesterday.)

**Comment by lucaszanella** [comment]
I don't know what I did, I'm on the phone right now. It looks like I messed up then because my repo was using the modifications for the new / thing. Also I had solved another problem too that I don't remember which was. There were 2 related problems solved in my commits 😖. Mainly this confusion was because my ubuntu corrupted while installing updates and I had to redownload everything

Enviado via ProtonMail móvel

-------- Mensagem Original --------
Ativo 19 de ago. de 2021 15:09, Scott Lamb escreveu:

**Comment by lucaszanella** [comment]
I thought I had wiped everything with a force push but no, my fixes are still there. Are you saying I inserted the wrong URL in the test? Could you tell me exactly what's happening? I'd like to jump to the other issues because I'm confused with this one

**Comment by scottlamb** [comment]
I think it might just be easiest to say through code. Please take a look at #20.

**Comment by lucaszanella** [comment]
Awesome, thanks for doing the rest. Did these modifications work for your cameras? It works for the .txt files but did everything go alright for you? Can we focus on the h264 error?

**Comment by scottlamb** [comment]
Yes, everything seems to work for me. Merged #20.

**Pull request closed without merging**
